package com.dranant.block;

import net.minecraft.core.Direction;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.phys.shapes.Shapes;
import net.minecraft.world.phys.shapes.VoxelShape;

import java.util.EnumMap;
import java.util.Map;

/**
 * Modern HD furniture pieces - GENERATED by tools/gen_furniture.py together with the block models and 64x64 HD textures.
 * Boxes are authored facing NORTH in pixels; shapes are rotated for every facing.
 */
public enum FurnitureType {
    MODERN_SOFA("modern_sofa", "Modern Sofa", 9, 0, false,
            new double[][]{{0, 2, 1, 16, 6, 16}, {2, 6, 1.5, 14, 9, 13}, {2, 6, 12, 14, 15, 16}, {0, 6, 2, 2, 11, 16}, {14, 6, 2, 16, 11, 16}, {10.5, 9, 9.5, 13.5, 13, 11.5}, {1, 0, 2, 2, 2, 3}, {1, 0, 14, 2, 2, 15}, {14, 0, 2, 15, 2, 3}, {14, 0, 14, 15, 2, 15}},
            new double[0][]),
    COFFEE_TABLE("coffee_table", "Marble Coffee Table", 0, 0, false,
            new double[][]{{0, 7, 0, 16, 8.5, 16}, {2, 2, 2, 14, 3, 14}, {1.5, 0, 1.5, 2.5, 7, 2.5}, {1.5, 0, 13.5, 2.5, 7, 14.5}, {13.5, 0, 1.5, 14.5, 7, 2.5}, {13.5, 0, 13.5, 14.5, 7, 14.5}},
            new double[0][]),
    TV_STAND("tv_stand", "Smart TV & Media Unit", 0, 4, false,
            new double[][]{{0, 0, 5, 16, 5, 15}, {0, 5, 5, 16, 5.5, 15}, {7, 5.5, 9, 9, 7, 11}, {0, 7, 9.5, 16, 16, 10.5}},
            new double[0][]),
    DINING_TABLE("dining_table", "Walnut Dining Table", 0, 0, false,
            new double[][]{{0, 14, 0, 16, 16, 16}, {1.5, 0, 1.5, 3, 14, 3}, {13, 0, 1.5, 14.5, 14, 3}, {1.5, 0, 13, 3, 14, 14.5}, {13, 0, 13, 14.5, 14, 14.5}, {3, 12, 2, 13, 13.5, 3}, {3, 12, 13, 13, 13.5, 14}},
            new double[0][]),
    DINING_CHAIR("dining_chair", "Designer Chair", 8, 0, false,
            new double[][]{{2.5, 7, 2.5, 13.5, 9, 13.5}, {2.5, 9, 12, 13.5, 16, 13.5}, {3, 0, 3, 4.2, 7, 4.2}, {3, 0, 11.8, 4.2, 7, 13}, {11.8, 0, 3, 13, 7, 4.2}, {11.8, 0, 11.8, 13, 7, 13}},
            new double[0][]),
    KITCHEN_COUNTER("kitchen_counter", "Kitchen Counter", 0, 0, false,
            new double[][]{{1, 0, 2, 15, 1, 15}, {0, 1, 1, 16, 14, 16}, {0, 14, 0, 16, 16, 16}},
            new double[0][]),
    KITCHEN_SINK("kitchen_sink", "Kitchen Sink", 0, 0, false,
            new double[][]{{1, 0, 2, 15, 1, 15}, {0, 1, 1, 16, 12, 16}, {0, 14, 0, 16, 16, 3}, {0, 14, 13, 16, 16, 16}, {0, 14, 3, 3, 16, 13}, {13, 14, 3, 16, 16, 13}, {3, 12, 3, 13, 13, 13}, {3, 13, 3, 13, 14, 3.5}, {3, 13, 12.5, 13, 14, 13}},
            new double[0][]),
    KITCHEN_STOVE("kitchen_stove", "Induction Range", 0, 0, false,
            new double[][]{{1, 0, 2, 15, 1, 15}, {0, 1, 1, 16, 14, 16}, {0, 14, 0, 16, 16, 16}},
            new double[0][]),
    FRIDGE("fridge", "French-Door Fridge", 0, 0, true,
            new double[][]{{0, 0, 1, 16, 16, 16}},
            new double[][]{{0, 0, 1, 16, 15, 16}, {0, 15, 1, 16, 16, 16}}),
    FLOOR_LAMP("floor_lamp", "Arc Floor Lamp", 0, 15, false,
            new double[][]{{4.5, 0, 4.5, 11.5, 1, 11.5}, {7.5, 1, 7.5, 8.5, 11, 8.5}, {4, 11, 4, 12, 16, 12}},
            new double[0][]),
    OFFICE_DESK("office_desk", "Workstation Desk", 0, 3, false,
            new double[][]{{0, 12, 0, 16, 13, 16}, {0.5, 0, 1, 1.5, 12, 15}, {14.5, 0, 1, 15.5, 12, 15}, {1.5, 6, 14, 14.5, 12, 15}, {7, 13, 11, 9, 15, 13}, {2, 15, 11.5, 14, 16, 12.5}, {3, 13, 3, 13, 13.5, 7}, {13.5, 13, 4, 15, 13.6, 6.5}},
            new double[0][]),
    MODERN_TOILET("modern_toilet", "Wall-Hung Toilet", 7, 0, false,
            new double[][]{{4, 3, 4, 12, 7, 15}, {3.5, 7, 3.5, 12.5, 7.6, 14}, {3, 3, 14, 13, 15, 16}, {7, 13, 15.5, 9, 14, 16.5}},
            new double[0][]),
    BATHROOM_VANITY("bathroom_vanity", "Bathroom Vanity & Mirror", 0, 6, false,
            new double[][]{{0, 3, 4, 16, 11, 16}, {0, 11, 3, 16, 12, 16}, {3, 12, 5, 13, 14.5, 13}, {7.5, 12, 13.5, 8.5, 16, 14.5}},
            new double[0][]);

    private final String id;
    private final String title;
    private final int seatHeight;
    private final int light;
    private final boolean tall;
    private final Map<Direction, VoxelShape> lower = new EnumMap<>(Direction.class);
    private final Map<Direction, VoxelShape> upper = new EnumMap<>(Direction.class);

    FurnitureType(String id, String title, int seatHeight, int light, boolean tall, double[][] lowerBoxes, double[][] upperBoxes) {
        this.id = id;
        this.title = title;
        this.seatHeight = seatHeight;
        this.light = light;
        this.tall = tall;
        for (Direction d : Direction.Plane.HORIZONTAL) {
            lower.put(d, shape(lowerBoxes, d));
            upper.put(d, shape(upperBoxes, d));
        }
    }

    private static VoxelShape shape(double[][] boxes, Direction facing) {
        VoxelShape s = Shapes.empty();
        for (double[] b : boxes) {
            double x0 = b[0], z0 = b[2], x1 = b[3], z1 = b[5];
            double rx0, rz0, rx1, rz1;
            switch (facing) {
                case EAST -> { rx0 = 16 - z1; rz0 = x0; rx1 = 16 - z0; rz1 = x1; }
                case SOUTH -> { rx0 = 16 - x1; rz0 = 16 - z1; rx1 = 16 - x0; rz1 = 16 - z0; }
                case WEST -> { rx0 = z0; rz0 = 16 - x1; rx1 = z1; rz1 = 16 - x0; }
                default -> { rx0 = x0; rz0 = z0; rx1 = x1; rz1 = z1; }
            }
            s = Shapes.or(s, Block.box(rx0, b[1], rz0, rx1, b[4], rz1));
        }
        return s.isEmpty() ? Block.box(0, 0, 0, 16, 2, 16) : s.optimize();
    }

    public String id() { return id; }
    public String title() { return title; }
    /** Seat height in pixels (0 = not a seat). */
    public int seatHeight() { return seatHeight; }
    public int light() { return light; }
    public boolean tall() { return tall; }

    public VoxelShape shape(Direction facing, boolean upperHalf) {
        return (upperHalf ? upper : lower).get(facing);
    }
}
