package com.dranant.client.model;

import com.dranant.DoctorAnantMod;
import com.dranant.entity.SupercarEntity;
import com.dranant.entity.SupercarVariant;
import net.minecraft.client.model.HierarchicalModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.util.Mth;

/**
 * Supercar model - GENERATED by tools/gen_supercar.py together with its 4x HD textures (do not edit the layer by hand).
 * Front = -Z, +X = the car's left (driver) side. Doors open per model: scissor (Veloce), conventional (GT), gullwing (Phantom).
 * Bonnet and boot lift, front wheels steer, all wheels spin, the steering wheel turns, the Phantom's active wing rises at speed.
 */
public class SupercarModel extends HierarchicalModel<SupercarEntity> {
    public static final ModelLayerLocation LAYER = new ModelLayerLocation(DoctorAnantMod.id("supercar"), "main");
    public static final int TEX_WIDTH = 256, TEX_HEIGHT = 256;

    private final ModelPart root;
    private final ModelPart hood;
    private final ModelPart trunk;
    private final ModelPart doorL;
    private final ModelPart doorR;
    private final ModelPart steeringWheel;
    private final ModelPart wheelFl;
    private final ModelPart wheelFlSpin;
    private final ModelPart wheelFr;
    private final ModelPart wheelFrSpin;
    private final ModelPart wheelRl;
    private final ModelPart wheelRlSpin;
    private final ModelPart wheelRr;
    private final ModelPart wheelRrSpin;
    private final ModelPart wingGt;
    private final ModelPart ducktail;
    private final ModelPart activeWing;

    public SupercarModel(ModelPart root) {
        this.root = root;
        this.hood = root.getChild("body").getChild("hood");
        this.trunk = root.getChild("body").getChild("trunk");
        this.doorL = root.getChild("body").getChild("door_l");
        this.doorR = root.getChild("body").getChild("door_r");
        this.steeringWheel = root.getChild("body").getChild("steer").getChild("steer_wheel");
        this.wheelFl = root.getChild("body").getChild("wheel_fl");
        this.wheelFlSpin = root.getChild("body").getChild("wheel_fl").getChild("wheel_fl_spin");
        this.wheelFr = root.getChild("body").getChild("wheel_fr");
        this.wheelFrSpin = root.getChild("body").getChild("wheel_fr").getChild("wheel_fr_spin");
        this.wheelRl = root.getChild("body").getChild("wheel_rl");
        this.wheelRlSpin = root.getChild("body").getChild("wheel_rl").getChild("wheel_rl_spin");
        this.wheelRr = root.getChild("body").getChild("wheel_rr");
        this.wheelRrSpin = root.getChild("body").getChild("wheel_rr").getChild("wheel_rr_spin");
        this.wingGt = root.getChild("body").getChild("trunk").getChild("wing_gt");
        this.ducktail = root.getChild("body").getChild("trunk").getChild("ducktail");
        this.activeWing = root.getChild("body").getChild("trunk").getChild("active_wing");
    }

    public static LayerDefinition createLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p_body = root.addOrReplaceChild("body", CubeListBuilder.create()
                .texOffs(0, 0).addBox(-14F, 18F, -30F, 28F, 2F, 60F)
                .texOffs(76, 122).addBox(-11F, 12F, -30F, 22F, 6F, 16F)
                .texOffs(104, 195).addBox(-11F, 14F, -35F, 22F, 4F, 5F)
                .texOffs(208, 146).addBox(11F, 10F, -28F, 5F, 2F, 14F)
                .texOffs(0, 166).addBox(-16F, 10F, -28F, 5F, 2F, 14F)
                .texOffs(0, 195).addBox(11F, 13F, -33F, 5F, 5F, 5F)
                .texOffs(20, 195).addBox(-16F, 13F, -33F, 5F, 5F, 5F)
                .texOffs(154, 213).addBox(-14F, 18F, -36F, 28F, 1F, 3F)
                .texOffs(50, 219).addBox(-8F, 15F, -36F, 16F, 3F, 1F)
                .texOffs(116, 62).addBox(14F, 18F, -15F, 2F, 1F, 30F)
                .texOffs(180, 62).addBox(-16F, 18F, -15F, 2F, 1F, 30F)
                .texOffs(0, 62).addBox(-15F, 12F, -14F, 30F, 6F, 28F)
                .texOffs(68, 182).addBox(-13F, 4F, -3F, 26F, 1F, 11F)
                .texOffs(166, 205).addBox(-13F, 10F, -12F, 26F, 3F, 4F)
                .texOffs(92, 146).addBox(-2F, 13F, -10F, 4F, 4F, 16F)
                .texOffs(142, 182).addBox(2F, 14F, -3F, 9F, 3F, 8F)
                .texOffs(176, 182).addBox(-11F, 14F, -3F, 9F, 3F, 8F)
                .texOffs(210, 182).addBox(2F, 6F, 4F, 9F, 8F, 2F)
                .texOffs(232, 182).addBox(-11F, 6F, 4F, 9F, 8F, 2F)
                .texOffs(0, 205).addBox(-13F, 5F, 7F, 26F, 7F, 1F)
                .texOffs(38, 166).addBox(12F, 5F, 6F, 2F, 7F, 8F)
                .texOffs(58, 166).addBox(-14F, 5F, 6F, 2F, 7F, 8F)
                .texOffs(144, 96).addBox(-11F, 12F, 14F, 22F, 6F, 18F)
                .texOffs(0, 146).addBox(11F, 10F, 14F, 5F, 2F, 18F)
                .texOffs(46, 146).addBox(-16F, 10F, 14F, 5F, 2F, 18F)
                .texOffs(40, 195).addBox(11F, 12F, 28F, 5F, 6F, 4F)
                .texOffs(58, 195).addBox(-16F, 12F, 28F, 5F, 6F, 4F)
                .texOffs(0, 213).addBox(-14F, 18F, 30F, 28F, 2F, 4F)
                .texOffs(112, 219).addBox(-15F, 12F, 32F, 30F, 2F, 1F)
                .texOffs(174, 219).addBox(-4F, 14F, 32F, 8F, 2F, 1F)
                .texOffs(84, 219).addBox(3F, 16F, 32F, 3F, 2F, 2F)
                .texOffs(94, 219).addBox(-6F, 16F, 32F, 3F, 2F, 2F), PartPose.offset(0F, 0F, 0F));
        PartDefinition p_hood = p_body.addOrReplaceChild("hood", CubeListBuilder.create()
                .texOffs(132, 146).addBox(-11F, -1F, -16F, 22F, 1F, 16F), PartPose.offset(0F, 12F, -14F));
        PartDefinition p_nose_slope = p_hood.addOrReplaceChild("nose_slope", CubeListBuilder.create()
                .texOffs(158, 195).addBox(-11F, 0F, -7F, 22F, 1F, 7F), PartPose.offsetAndRotation(0F, -1F, -16F, 0.42F, 0F, 0F));
        PartDefinition p_trunk = p_body.addOrReplaceChild("trunk", CubeListBuilder.create()
                .texOffs(0, 182).addBox(-11F, -1F, 0F, 22F, 1F, 12F), PartPose.offset(0F, 12F, 20F));
        PartDefinition p_windshield = p_body.addOrReplaceChild("windshield", CubeListBuilder.create()
                .texOffs(78, 166).addBox(-12F, -13F, -0.5F, 24F, 13F, 1F), PartPose.offsetAndRotation(0F, 12F, -14F, -0.98F, 0F, 0F));
        PartDefinition p_rear_glass = p_body.addOrReplaceChild("rear_glass", CubeListBuilder.create()
                .texOffs(128, 166).addBox(-12F, 0F, -0.5F, 24F, 13F, 1F), PartPose.offsetAndRotation(0F, 4.5F, 8F, 1.08F, 0F, 0F));
        PartDefinition p_a_pillar_l = p_body.addOrReplaceChild("a_pillar_l", CubeListBuilder.create()
                .texOffs(178, 166).addBox(-1F, -13F, -0.5F, 2F, 13F, 1F), PartPose.offsetAndRotation(13F, 12F, -14F, -0.98F, 0F, 0F));
        PartDefinition p_c_pillar_l = p_body.addOrReplaceChild("c_pillar_l", CubeListBuilder.create()
                .texOffs(184, 166).addBox(-1F, 0F, -0.5F, 2F, 13F, 1F), PartPose.offsetAndRotation(13F, 4.5F, 8F, 1.08F, 0F, 0F));
        PartDefinition p_fender_slope_l = p_body.addOrReplaceChild("fender_slope_l", CubeListBuilder.create()
                .texOffs(54, 205).addBox(0F, 0F, -6F, 5F, 2F, 6F), PartPose.offsetAndRotation(11F, 10F, -28F, 0.45F, 0F, 0F));
        PartDefinition p_headlight_l = p_fender_slope_l.addOrReplaceChild("headlight_l", CubeListBuilder.create()
                .texOffs(122, 213).addBox(0.5F, -0.5F, -5.5F, 4F, 1F, 4F), PartPose.offset(0F, 0F, 0F));
        PartDefinition p_door_l = p_body.addOrReplaceChild("door_l", CubeListBuilder.create()
                .texOffs(0, 122).addBox(-0.5F, 0F, 0F, 1F, 6F, 18F)
                .texOffs(192, 219).addBox(0.5F, -2F, 1F, 3F, 2F, 1F), PartPose.offset(15.5F, 12F, -12F));
        PartDefinition p_door_l_glass = p_door_l.addOrReplaceChild("door_l_glass", CubeListBuilder.create()
                .texOffs(152, 122).addBox(-0.5F, -8F, 2F, 1F, 8F, 14F), PartPose.offsetAndRotation(0F, 0F, 0F, 0F, 0F, -0.3F));
        PartDefinition p_a_pillar_r = p_body.addOrReplaceChild("a_pillar_r", CubeListBuilder.create()
                .texOffs(190, 166).addBox(-1F, -13F, -0.5F, 2F, 13F, 1F), PartPose.offsetAndRotation(-13F, 12F, -14F, -0.98F, 0F, 0F));
        PartDefinition p_c_pillar_r = p_body.addOrReplaceChild("c_pillar_r", CubeListBuilder.create()
                .texOffs(196, 166).addBox(-1F, 0F, -0.5F, 2F, 13F, 1F), PartPose.offsetAndRotation(-13F, 4.5F, 8F, 1.08F, 0F, 0F));
        PartDefinition p_fender_slope_r = p_body.addOrReplaceChild("fender_slope_r", CubeListBuilder.create()
                .texOffs(76, 205).addBox(0F, 0F, -6F, 5F, 2F, 6F), PartPose.offsetAndRotation(-16F, 10F, -28F, 0.45F, 0F, 0F));
        PartDefinition p_headlight_r = p_fender_slope_r.addOrReplaceChild("headlight_r", CubeListBuilder.create()
                .texOffs(138, 213).addBox(0.5F, -0.5F, -5.5F, 4F, 1F, 4F), PartPose.offset(0F, 0F, 0F));
        PartDefinition p_door_r = p_body.addOrReplaceChild("door_r", CubeListBuilder.create()
                .texOffs(38, 122).addBox(-0.5F, 0F, 0F, 1F, 6F, 18F)
                .texOffs(200, 219).addBox(-3.5F, -2F, 1F, 3F, 2F, 1F), PartPose.offset(-15.5F, 12F, -12F));
        PartDefinition p_door_r_glass = p_door_r.addOrReplaceChild("door_r_glass", CubeListBuilder.create()
                .texOffs(182, 122).addBox(-0.5F, -8F, 2F, 1F, 8F, 14F), PartPose.offsetAndRotation(0F, 0F, 0F, 0F, 0F, 0.3F));
        PartDefinition p_steer = p_body.addOrReplaceChild("steer", CubeListBuilder.create()
                .texOffs(104, 219).addBox(-0.5F, -0.5F, -3.5F, 1F, 1F, 3F), PartPose.offsetAndRotation(6.5F, 10.5F, -7.5F, -0.35F, 0F, 0F));
        PartDefinition p_steer_wheel = p_steer.addOrReplaceChild("steer_wheel", CubeListBuilder.create()
                .texOffs(226, 205).addBox(-3F, -3F, -0.5F, 6F, 6F, 1F), PartPose.offset(0F, 0F, 0F));
        PartDefinition p_wheel_fl = p_body.addOrReplaceChild("wheel_fl", CubeListBuilder.create(), PartPose.offset(13.5F, 17.5F, -21F));
        PartDefinition p_wheel_fl_spin = p_wheel_fl.addOrReplaceChild("wheel_fl_spin", CubeListBuilder.create(), PartPose.offset(0F, 0F, 0F));
        PartDefinition p_wheel_fl_s0 = p_wheel_fl_spin.addOrReplaceChild("wheel_fl_s0", CubeListBuilder.create()
                .texOffs(0, 96).addBox(-2.5F, -6.5F, -6.5F, 5F, 13F, 13F), PartPose.offset(0F, 0F, 0F));
        PartDefinition p_wheel_fl_s1 = p_wheel_fl_spin.addOrReplaceChild("wheel_fl_s1", CubeListBuilder.create()
                .texOffs(36, 96).addBox(-2.4F, -6.5F, -6.5F, 4.8F, 13F, 13F), PartPose.offsetAndRotation(0F, 0F, 0F, 0.3927F, 0F, 0F));
        PartDefinition p_wheel_fl_s2 = p_wheel_fl_spin.addOrReplaceChild("wheel_fl_s2", CubeListBuilder.create()
                .texOffs(72, 96).addBox(-2.4F, -6.5F, -6.5F, 4.8F, 13F, 13F), PartPose.offsetAndRotation(0F, 0F, 0F, 0.7854F, 0F, 0F));
        PartDefinition p_wheel_fl_s3 = p_wheel_fl_spin.addOrReplaceChild("wheel_fl_s3", CubeListBuilder.create()
                .texOffs(108, 96).addBox(-2.4F, -6.5F, -6.5F, 4.8F, 13F, 13F), PartPose.offsetAndRotation(0F, 0F, 0F, 1.1781F, 0F, 0F));
        PartDefinition p_wheel_fr = p_body.addOrReplaceChild("wheel_fr", CubeListBuilder.create(), PartPose.offset(-13.5F, 17.5F, -21F));
        PartDefinition p_wheel_fr_spin = p_wheel_fr.addOrReplaceChild("wheel_fr_spin", CubeListBuilder.create(), PartPose.offset(0F, 0F, 0F));
        PartDefinition p_wheel_fr_s0 = p_wheel_fr_spin.addOrReplaceChild("wheel_fr_s0", CubeListBuilder.create()
                .texOffs(0, 96).addBox(-2.5F, -6.5F, -6.5F, 5F, 13F, 13F), PartPose.offset(0F, 0F, 0F));
        PartDefinition p_wheel_fr_s1 = p_wheel_fr_spin.addOrReplaceChild("wheel_fr_s1", CubeListBuilder.create()
                .texOffs(36, 96).addBox(-2.4F, -6.5F, -6.5F, 4.8F, 13F, 13F), PartPose.offsetAndRotation(0F, 0F, 0F, 0.3927F, 0F, 0F));
        PartDefinition p_wheel_fr_s2 = p_wheel_fr_spin.addOrReplaceChild("wheel_fr_s2", CubeListBuilder.create()
                .texOffs(72, 96).addBox(-2.4F, -6.5F, -6.5F, 4.8F, 13F, 13F), PartPose.offsetAndRotation(0F, 0F, 0F, 0.7854F, 0F, 0F));
        PartDefinition p_wheel_fr_s3 = p_wheel_fr_spin.addOrReplaceChild("wheel_fr_s3", CubeListBuilder.create()
                .texOffs(108, 96).addBox(-2.4F, -6.5F, -6.5F, 4.8F, 13F, 13F), PartPose.offsetAndRotation(0F, 0F, 0F, 1.1781F, 0F, 0F));
        PartDefinition p_wheel_rl = p_body.addOrReplaceChild("wheel_rl", CubeListBuilder.create(), PartPose.offset(13.5F, 17.5F, 21F));
        PartDefinition p_wheel_rl_spin = p_wheel_rl.addOrReplaceChild("wheel_rl_spin", CubeListBuilder.create(), PartPose.offset(0F, 0F, 0F));
        PartDefinition p_wheel_rl_s0 = p_wheel_rl_spin.addOrReplaceChild("wheel_rl_s0", CubeListBuilder.create()
                .texOffs(0, 96).addBox(-2.5F, -6.5F, -6.5F, 5F, 13F, 13F), PartPose.offset(0F, 0F, 0F));
        PartDefinition p_wheel_rl_s1 = p_wheel_rl_spin.addOrReplaceChild("wheel_rl_s1", CubeListBuilder.create()
                .texOffs(36, 96).addBox(-2.4F, -6.5F, -6.5F, 4.8F, 13F, 13F), PartPose.offsetAndRotation(0F, 0F, 0F, 0.3927F, 0F, 0F));
        PartDefinition p_wheel_rl_s2 = p_wheel_rl_spin.addOrReplaceChild("wheel_rl_s2", CubeListBuilder.create()
                .texOffs(72, 96).addBox(-2.4F, -6.5F, -6.5F, 4.8F, 13F, 13F), PartPose.offsetAndRotation(0F, 0F, 0F, 0.7854F, 0F, 0F));
        PartDefinition p_wheel_rl_s3 = p_wheel_rl_spin.addOrReplaceChild("wheel_rl_s3", CubeListBuilder.create()
                .texOffs(108, 96).addBox(-2.4F, -6.5F, -6.5F, 4.8F, 13F, 13F), PartPose.offsetAndRotation(0F, 0F, 0F, 1.1781F, 0F, 0F));
        PartDefinition p_wheel_rr = p_body.addOrReplaceChild("wheel_rr", CubeListBuilder.create(), PartPose.offset(-13.5F, 17.5F, 21F));
        PartDefinition p_wheel_rr_spin = p_wheel_rr.addOrReplaceChild("wheel_rr_spin", CubeListBuilder.create(), PartPose.offset(0F, 0F, 0F));
        PartDefinition p_wheel_rr_s0 = p_wheel_rr_spin.addOrReplaceChild("wheel_rr_s0", CubeListBuilder.create()
                .texOffs(0, 96).addBox(-2.5F, -6.5F, -6.5F, 5F, 13F, 13F), PartPose.offset(0F, 0F, 0F));
        PartDefinition p_wheel_rr_s1 = p_wheel_rr_spin.addOrReplaceChild("wheel_rr_s1", CubeListBuilder.create()
                .texOffs(36, 96).addBox(-2.4F, -6.5F, -6.5F, 4.8F, 13F, 13F), PartPose.offsetAndRotation(0F, 0F, 0F, 0.3927F, 0F, 0F));
        PartDefinition p_wheel_rr_s2 = p_wheel_rr_spin.addOrReplaceChild("wheel_rr_s2", CubeListBuilder.create()
                .texOffs(72, 96).addBox(-2.4F, -6.5F, -6.5F, 4.8F, 13F, 13F), PartPose.offsetAndRotation(0F, 0F, 0F, 0.7854F, 0F, 0F));
        PartDefinition p_wheel_rr_s3 = p_wheel_rr_spin.addOrReplaceChild("wheel_rr_s3", CubeListBuilder.create()
                .texOffs(108, 96).addBox(-2.4F, -6.5F, -6.5F, 4.8F, 13F, 13F), PartPose.offsetAndRotation(0F, 0F, 0F, 1.1781F, 0F, 0F));
        PartDefinition p_wing_gt = p_trunk.addOrReplaceChild("wing_gt", CubeListBuilder.create()
                .texOffs(98, 205).addBox(-14F, 5F, 26F, 28F, 1F, 6F)
                .texOffs(76, 195).addBox(14F, 3F, 26F, 1F, 4F, 6F)
                .texOffs(90, 195).addBox(-15F, 3F, 26F, 1F, 4F, 6F)
                .texOffs(240, 205).addBox(6F, 6F, 28F, 1F, 5F, 2F)
                .texOffs(246, 205).addBox(-7F, 6F, 28F, 1F, 5F, 2F), PartPose.offset(0F, -12F, -20F));
        PartDefinition p_ducktail = p_trunk.addOrReplaceChild("ducktail", CubeListBuilder.create()
                .texOffs(0, 219).addBox(-11F, 10F, 29F, 22F, 1F, 3F), PartPose.offset(0F, -12F, -20F));
        PartDefinition p_active_wing = p_trunk.addOrReplaceChild("active_wing", CubeListBuilder.create()
                .texOffs(64, 213).addBox(-12F, -1F, -2F, 24F, 1F, 5F)
                .texOffs(208, 219).addBox(5F, 0F, 0F, 1F, 2F, 1F)
                .texOffs(212, 219).addBox(-6F, 0F, 0F, 1F, 2F, 1F), PartPose.offset(0F, -1F, 8F));
        return LayerDefinition.create(mesh, TEX_WIDTH, TEX_HEIGHT);
    }

    @Override
    public ModelPart root() {
        return root;
    }

    @Override
    public void setupAnim(SupercarEntity entity, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {
    }

    /** Poses every moving part for this frame. */
    public void pose(SupercarEntity car, float partialTick) {
        root.getAllParts().forEach(ModelPart::resetPose);
        SupercarVariant variant = car.getVariant();
        float spin = car.getWheelSpin(partialTick);
        float steer = car.getVisualSteer(partialTick);
        for (ModelPart w : new ModelPart[]{wheelFlSpin, wheelFrSpin, wheelRlSpin, wheelRrSpin}) w.xRot = -spin;
        wheelFl.yRot = steer * 0.55F;
        wheelFr.yRot = steer * 0.55F;
        steeringWheel.zRot = -steer * 2.4F;

        wingGt.visible = variant == SupercarVariant.GT;
        ducktail.visible = variant == SupercarVariant.VELOCE;
        activeWing.visible = variant == SupercarVariant.PHANTOM;
        activeWing.y -= 3.5F * car.getWingLift(partialTick);

        hood.xRot = -1.05F * ease(car.getPartOpen(SupercarEntity.PART_HOOD, partialTick));
        trunk.xRot = 1.0F * ease(car.getPartOpen(SupercarEntity.PART_TRUNK, partialTick));
        poseDoor(doorL, 1, ease(car.getPartOpen(SupercarEntity.PART_DOOR_LEFT, partialTick)), variant);
        poseDoor(doorR, -1, ease(car.getPartOpen(SupercarEntity.PART_DOOR_RIGHT, partialTick)), variant);
    }

    private static void poseDoor(ModelPart door, int side, float t, SupercarVariant variant) {
        if (t <= 0.0F) return;
        switch (variant.doorStyle()) {
            case SCISSOR -> door.xRot = 1.25F * t;                    // swings straight up about the front hinge
            case CONVENTIONAL -> door.yRot = 1.15F * t * side;       // swings outward
            case GULLWING -> {
                // hinge along the roof edge: rotate about (13*side, 4.5) instead of the door's own pivot
                float a = -1.45F * t * side;
                float vx = (13.0F - 15.5F) * side, vy = 4.5F - 11.0F;
                float cos = Mth.cos(a), sin = Mth.sin(a);
                door.zRot = a;
                door.x += vx - (vx * cos - vy * sin);
                door.y += vy - (vx * sin + vy * cos);
            }
        }
    }

    private static float ease(float t) {
        return t * t * (3.0F - 2.0F * t);
    }
}
